apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: In
            values:
            - expense            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

  tolerations:
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"  


# kubectl label nodes <your-node-name> project=expense  

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd          
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

# kubectl label nodes <your-node-name> disktype=ssd