apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #IfNotPresent
  tolerations:
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"


# kubectl taint nodes node-123 project=expense:NoScxhedule    
